### ISSUE TITLE
How to custom error 403 pages with 403.balde.php

### ISSUE THREAD

**Issue by AFSDARIF** [mrofi/laravel-shared-hosting-package#1]
how do I get the url **project.com/app** issued **403 error** pages are in custom? such as a **404 error** page (ex: **project.com/appabcdshasgha**). please help me,

**Comment by mrofi** [comment]
you can add this code line in your .htaccess

ErrorDocument 403 /your_project_folder/index.php
or
ErrorDocument 403 index.php

**Comment by AFSDARIF** [comment]
wow, this works very much helped by ini.I thank you thank you very much.

but if this can work well when implemented for all types of error pages? such as 500.503, and so on.

**Comment by mrofi** [comment]
Yeah of course.

you can find out more about this custom error in the documentatiion [here](https://httpd.apache.org/docs/2.4/custom-error.html)

**Comment by AFSDARIF** [comment]
oke thanks

**Comment by mrofi** [comment]
You are welcome :-)
